### ISSUE TITLE
Don't work on Windows 10

### ISSUE THREAD

**Issue by albertoa73** [leondz/tiamatregular#1]
Hello @leondz ,
I'm trying install the OTF on Ms Windows 10. But I receive the message "The requested file tiamat.otf is not a valid font file."

**Comment by DarkRoastOtter** [comment]
I'm having the same issue. No matter what I do it's not able to install the OTF version, which should be a valid file.

**Comment by Daizuko** [comment]
I can't get them to work on MacOS Mojave either.

**Comment by scottzirkel** [comment]
They installed for me on Mojave, but did have some minor issues with the tables.

**Edit:** Never mind. The OTF installed, but doesn't show up in any apps, only Font Book. Acts like there's duplicates, even though there aren't.

**Comment by leondz** [comment]
Hey,

Yeah, I agree. For Mac I used these: 
https://www.reddit.com/r/UnearthedArcana/comments/3vpphx/5e_font_package_embeddable_cc_edition/ 
combined with the fixed for some bold/italic variants here: 
https://www.reddit.com/r/UnearthedArcana/comments/4loka0/fixed_versions_of_solberas_fonts/
